version: '3'

services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - GO_ENV=development

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    user: root
    volumes:
      - ./client:/app
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:8080
