version: '3'

services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - GO_ENV=development

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    user: root
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=https://verbose-carnival-x6pr4pv9pwh6g6v-8080.app.github.dev
