version: '3.8'

services:
  app:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - ngrok
      
  ngrok:
    image: wernight/ngrok
    command: ngrok http app:9000
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=<token>