version: '3.8'

services:
  app:
    build: .
    ports:
      - "9000:9000"

  ngrok:
    image: ngrok/ngrok:latest
    command: http app:9000
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=<paste token>
    depends_on:
      - app
